"""
Design Chat Session Manager

Manages persistent design chat sessions with:
- Server-side conversation storage (no need to send full history each call)
- Sliding window compression: recent N turns kept verbatim, older turns summarized
- Token budget control: keeps total context under a budget
- Decision extraction: keyword-based + optional LLM extraction of key decisions

Architecture:
  Client sends: session_id + new message
  Server loads: compressed_summary + recent_turns + RAG + new message
  Result: consistent ~7K token context regardless of conversation length
"""
from __future__ import annotations

import json
import logging
import os
import time
from contextlib import contextmanager
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

from .agent.context_manager import SessionCompressionContext
from .common.file_lock import cross_process_flock

logger = logging.getLogger(__name__)


@dataclass
class DesignSession:
    """A persistent design chat session."""
    session_id: str
    created_at: float = field(default_factory=time.time)
    updated_at: float = field(default_factory=time.time)
    # Full conversation: [{role: "user"|"assistant", content: str, timestamp: float}]
    turns: list[dict[str, Any]] = field(default_factory=list)
    # Compressed summary of older turns (generated by LLM)
    compressed_summary: str = ""
    # How many turns are covered by the compressed summary.
    # ABSOLUTE index over the whole history (archived + active turns).
    compressed_up_to: int = 0
    # How many turns were moved to the append-only archive file
    # (<session>.archive.jsonl). turns[i]'s absolute index = archived_count + i.
    archived_count: int = 0
    # Accumulated decisions/insights from the conversation
    decisions: list[str] = field(default_factory=list)
    # (code_snippets and tool_file_reads fields removed — were no-op for many releases)
    chat_mode: str = "code"


class DesignSessionManager:
    """Manages design chat sessions with persistence and compression."""

    def __init__(self, repo_root: str):
        self.repo_root = Path(repo_root)
        self.sessions_dir = self.repo_root / ".asicode" / "design_sessions"
        self.sessions_dir.mkdir(parents=True, exist_ok=True)
        # In-memory cache
        self._cache: dict[str, DesignSession] = {}
        # _save is called from both the main thread (add_turn) and the background compress thread (persist callback)
        # — atomic protection for archive migration + active file writes
        import threading as _threading
        self._save_lock = _threading.Lock()
        # Identifier for this process (terminal) — marks in_progress ownership in multi-terminal shared sessions
        # and distinguishes "my turn / another's turn" during context building
        self._owner = f"pid:{os.getpid()}"
        # Per-session disk mtime at last sync — detects changes from other processes
        self._mtimes: dict[str, float] = {}
        # Remembers "dead PIDs" for zombie in_progress turn detection — once judged dead,
        # a PID is cached for the process lifetime (PID-reuse false negatives are safe:
        # a zombie just lingers without corrupting data).
        self._dead_pids: set[int] = set()
        # (Decision extractor removed — was dead code)
        # Delegate context management to SessionCompressionContext
        self._ctx = SessionCompressionContext(repo_root)

    def get_or_create(self, session_id: str) -> DesignSession:
        """Load existing session or create new one.

        On cache hit, checks disk mtime and absorbs changes written by other
        processes (terminals) in-place — prevents turns from being invisible or
        overwritten when two asi share the same session.
        """
        if session_id in self._cache:
            session = self._cache[session_id]
            self._refresh_if_stale(session)
            return session

        session = self._load_raw(session_id)
        if session is not None:
            # Migration: preserve=True → exclude_from_compression=True
            # (legacy key removed from codebase but may exist in old session files)
            migrated = False
            for t in session.turns:
                if t.pop("preserve", None) is True:
                    t["exclude_from_compression"] = True
                    migrated = True
            if migrated:
                logger.info("Migrated preserve→exclude_from_compression in session %s", session_id)
            self._cache[session_id] = session
            try:
                self._mtimes[session_id] = self._session_path(session_id).stat().st_mtime
            except OSError:
                pass
            return session

        session = DesignSession(session_id=session_id)
        self._cache[session_id] = session
        return session

    def _load_raw(self, session_id: str) -> Optional[DesignSession]:
        """Load session directly from disk (no cache). Returns None if missing or corrupt."""
        path = self._session_path(session_id)
        if not path.exists():
            return None
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            return DesignSession(
                session_id=data.get("session_id", session_id),
                created_at=data.get("created_at", time.time()),
                updated_at=data.get("updated_at", time.time()),
                turns=data.get("turns", []),
                compressed_summary=data.get("compressed_summary", ""),
                compressed_up_to=data.get("compressed_up_to", 0),
                archived_count=data.get("archived_count", 0),
                decisions=data.get("decisions", []),
                chat_mode=data.get("chat_mode", "code"),
            )
        except Exception as e:
            logger.warning("Failed to load session %s: %s", session_id, e)
            return None

    @contextmanager
    def _flock(self, session_id: str):
        """Cross-process exclusive lock — protects read-modify-write cycle.

        The existing _save_lock (threading.Lock) is process-internal only, so two
        asi instances can still overwrite the same session file via last-writer-wins.
        No-op on platforms without fcntl (preserves existing behavior)."""
        lock_path = self.sessions_dir / f"{self._safe_id(session_id)}.lock"
        with cross_process_flock(lock_path):
            yield

    def _refresh_if_stale(self, session: DesignSession) -> None:
        """Absorb disk state if disk mtime differs from last sync timestamp."""
        path = self._session_path(session.session_id)
        try:
            mtime = path.stat().st_mtime
        except OSError:
            return
        if mtime == self._mtimes.get(session.session_id):
            return
        with self._save_lock:
            with self._flock(session.session_id):
                try:
                    self._adopt_from_disk(session, full=True)
                    self._mtimes[session.session_id] = path.stat().st_mtime
                except Exception as e:
                    logger.debug("Session refresh failed for %s: %s", session.session_id, e)

    def _adopt_from_disk(self, session: DesignSession, full: bool = False) -> None:
        """Merge the latest disk state into the cached session object in-place (caller must hold lock).

        Called before every read-modify-write to avoid losing turns appended by other processes.
        - turns: uses the side with more archive progress as base, then appends the other's
          newer (by timestamp) turns behind. Adopts disk-side turn dicts, so in_progress
          flags released by other processes are absorbed too.
        - compression/archive pointers: monotonic → adopts the more advanced value
        - full=True: also adopts chat_mode/pending_spec/decisions from disk
          (mtime refresh path — when there are no unsaved local changes)
        In-place update (not object replacement): safe even when a background compress
        thread holds a reference to the same session object.
        """
        fresh = self._load_raw(session.session_id)
        if fresh is None:
            return
        if fresh.archived_count >= session.archived_count:
            base_turns, base_arch, other_turns = fresh.turns, fresh.archived_count, session.turns
        else:
            base_turns, base_arch, other_turns = session.turns, session.archived_count, fresh.turns
        # If base is empty, merge all other_turns from 0
        # (base_arch holds the newest archive pointer, so no duplicates)
        newest = base_turns[-1].get("timestamp", 0.0) if base_turns else 0.0
        merged = list(base_turns)
        for t in other_turns:
            if t.get("timestamp", 0.0) > newest:
                merged.append(t)
        session.turns[:] = merged
        session.archived_count = base_arch
        if fresh.compressed_up_to > session.compressed_up_to:
            session.compressed_up_to = fresh.compressed_up_to
            if fresh.compressed_summary:
                session.compressed_summary = fresh.compressed_summary
        session.updated_at = max(session.updated_at, fresh.updated_at)
        if full:
            session.chat_mode = fresh.chat_mode
            session.decisions = fresh.decisions

    def add_turn(self, session_id: str, role: str, content: str, model: str = "", preserve: bool = False, digest: str = "", exclude_from_compression: bool = False, in_progress: bool = False, tool_results: Optional[list] = None, auto: bool = False) -> None:
        """Add a turn to the session.

        digest: deterministic work-state digest of the turn's tool loop
        (files read/modified, commands run — see work_state_digest.py).
        Re-injected into context by build_context_messages so the next turn
        knows what this turn touched, even though tool messages are discarded.

        exclude_from_compression: if True, this turn is omitted from both the
        LLM summary prompt and verbatim re-insertion.  Use for ephemeral turns
        (e.g. tool call output logs) that are meaningful only to the immediately
        following turn and have no long-term value.

        in_progress: In multi-terminal shared sessions, marks that this user turn is still being
        processed (tool loop in progress). Automatically released when this process writes
        an assistant turn. Other processes' build_context_messages render unresolved
        user turns with an [IN-PROGRESS IN ANOTHER TERMINAL] system label to avoid
        conflating them with the current request.

        auto: True when this turn was produced by the auto-continue loop (countdown-
        submitted input, not a human keystroke). Persisted so the chain of self-driven
        steps can be reconstructed post-hoc and later used as data for repetition/
        loop-detection. Only stored when True to keep non-auto turns lean.
        """
        session = self.get_or_create(session_id)

        turn: dict = {
            "role": role,
            "content": content,
            "timestamp": time.time(),
        }
        if model:
            turn["model"] = model
        if preserve:
            turn["preserve"] = True
        if digest:
            turn["digest"] = digest
        if exclude_from_compression:
            turn["exclude_from_compression"] = True
        if in_progress and role == "user":
            turn["in_progress"] = True
            turn["owner"] = self._owner
        if auto:
            turn["auto"] = True
        # On ESC abort, persist tool_results in full — so the resume turn retains
        # read/modified details without loss. Normal complete turns do NOT forward them
        # (consistent with the existing policy that tool messages are discarded at turn end).
        # They get clipped by the rendering budget cap, and once pushed outside the
        # verbatim window they're auto-replaced by digest (summary→compress path).
        if tool_results and role == "assistant":
            turn["tool_results"] = tool_results

        with self._save_lock:
            with self._flock(session_id):
                # Absorb other processes' turns from disk first, then append —
                # prevents last-writer-wins overwrite from evaporating their turns
                try:
                    self._adopt_from_disk(session)
                except Exception as e:
                    logger.warning("adopt_from_disk failed for %s: %s", session_id, e)
                # Reap zombie in_progress turns from abnormally terminated parallel
                # terminals (or past lives of this process) — runs after adopt, before
                # append, so both the new assistant turn and the cleanup are in one
                # atomic write. Guarded for consistency with _save(): a corrupt
                # timestamp (e.g. explicit null on a manually edited turn) would
                # otherwise raise out of add_turn and abort the turn append.
                try:
                    self._reap_zombie_in_progress(session)
                except Exception as e:
                    logger.warning("reap_zombie failed for %s: %s", session_id, e)
                if role == "assistant":
                    self._clear_in_progress(session)
                    # Writing a new assistant turn means the previous turn's
                    # (whether aborted or completed) tool_results have served their purpose.
                    # tool_results exist only for "one turn after resume", so we clear
                    # the prior assistant turn's tool_results here. This makes ESC-aborted
                    # turns symmetric with normal complete turns ("tool messages are
                    # discarded at turn end"). From the next turn onward, only the
                    # digest is persistently referenced.
                    self._clear_prior_tool_results(session)
                session.turns.append(turn)
                session.updated_at = time.time()
                try:
                    self._write_session(session)
                except Exception as e:
                    logger.warning("Failed to save session %s: %s", session_id, e)

    def _clear_in_progress(self, session: DesignSession) -> None:
        """Release the most recent in_progress user turn owned by this process.

        An assistant turn being written means that request processing is complete."""
        for t in reversed(session.turns):
            if t.get("role") == "user" and t.get("in_progress") and t.get("owner") == self._owner:
                t.pop("in_progress", None)
                t.pop("owner", None)
                break

    def _clear_prior_tool_results(self, session: DesignSession) -> None:
        """Clear tool_results from the prior assistant turn.

        tool_results exist only to restore full context for exactly one turn
        after an ESC-aborted turn resumes. A new assistant turn being appended
        means that one turn has been consumed, so we clear it here. From the next
        turn onward, only the digest (deterministic file/tool level summary) is
        persistently referenced — same policy as normal complete turns.
        Targets only the most recent assistant turn (no reason for intermediate
        assistant turns to carry tool_results).
        """
        for t in reversed(session.turns):
            if t.get("role") == "assistant":
                if t.get("tool_results"):
                    t.pop("tool_results", None)
                break

    # Maximum duration (seconds) for an in_progress turn to be safely released — zombie recovery fallback.
    # Design chat can call tools up to DESIGN_CHAT_MAX_TOOL_ITERATIONS (500) times,
    # so a single response may take minutes. PID death is the primary signal; this value is the
    # fallback when PID info is absent (legacy owner) / test arbitrary owner strings,
    # and a safety net for extreme zombies like "PID alive but unresolved for days".
    _IN_PROGRESS_MAX_AGE = 3600  # 1 hour

    @staticmethod
    def _owner_pid(owner: str) -> Optional[int]:
        """Extract PID from owner string ("pid:1234"). Non-standard owner returns None."""
        if isinstance(owner, str) and owner.startswith("pid:"):
            try:
                return int(owner[4:])
            except ValueError:
                return None
        return None

    def _is_process_alive(self, pid: int) -> bool:
        """Determine if PID is an alive process (with caching).

        Checks via os.kill(pid, 0). PIDs once judged dead are permanently cached
        (safer to keep a zombie than resurrect one on PID reuse).
        """
        if pid in self._dead_pids:
            return False
        try:
            os.kill(pid, 0)
            return True
        except ProcessLookupError:
            self._dead_pids.add(pid)
            return False
        except (OSError, PermissionError):
            # Signal delivery failed for permission etc. — assume alive (conservative)
            return True

    def _reap_zombie_in_progress(self, session: DesignSession) -> bool:
        """Release in_progress user turns whose owner process died or which are too old.

        Called just before add_turn/_save to self-heal zombie turns left by abnormally
        terminated parallel terminals (or past lives before restart).

        Judgment priority:
          1. If owner PID is dead, release immediately (PID-based — immediate, binary)
          2. If PID is undetermined (legacy/test owner), release if age >= _IN_PROGRESS_MAX_AGE

        Even unresolved turns from self (self._owner) are caught here after restart
        (new PID) — the core path for SIGKILL/OOM recovery. Does not change locks/file
        state, only session.turns (caller holds the lock).
        Returns True if any turn was reaped (caller must persist to disk).
        """
        if not session.turns:
            return False
        now = time.time()
        reaped = False
        my_pid = self._owner_pid(self._owner)
        for t in session.turns:
            if t.get("role") != "user" or not t.get("in_progress"):
                continue
            owner = t.get("owner", "")
            pid = self._owner_pid(owner)
            should_reap = False
            if pid is not None:
                # Not our PID and dead → zombie. If it is our PID, it may still be
                # processing so we leave it alone — though this process cannot own an
                # unresolved turn from a past life (it has a new PID by add_turn time).
                if pid != my_pid and not self._is_process_alive(pid):
                    should_reap = True
            else:
                # owner is not in pid: form (legacy or test arbitrary string) —
                # fall back to age-based judgment only
                age = now - float(t.get("timestamp", now))
                if age >= self._IN_PROGRESS_MAX_AGE:
                    should_reap = True
            if should_reap:
                t.pop("in_progress", None)
                t.pop("owner", None)
                reaped = True
        return reaped

    def _load_project_context_md(self) -> str:
        """Delegate to SessionCompressionContext (mtime-cached)."""
        return self._ctx.load_project_context_md()

    def build_context_messages(
        self, session: DesignSession, current_model: str = "",
        system_chars: int = 0, skip_core_prompt: bool = False,
        mode: str = "",
    ) -> list[dict[str, str]]:
        """Delegate to SessionCompressionContext. If mode is empty, uses session.chat_mode."""
        if not mode:
            mode = getattr(session, "chat_mode", "code")
        return self._ctx.build_context_messages(
            session, current_model, system_chars, skip_core_prompt=skip_core_prompt,
            mode=mode, owner=self._owner,
        )

    # ── Delegated to SessionCompressionContext ─────────────────────────────────

    def schedule_background_compress(
        self,
        session: DesignSession,
        model: str,
        llm_client,
        system_chars: int = 0,
        force: bool = False,
        notify=None,
    ) -> None:
        """Delegate to SessionCompressionContext with persist callback."""
        self._ctx.schedule_background_compress(
            session, model, llm_client, system_chars, force=force,
            notify=notify,
            persist=lambda: self._save(session),
        )

    def compact_now(
        self, session: DesignSession, model: str, llm_client,
        recent_keep: int = 0, notify=None,
    ) -> bool:
        """Synchronously compress the recent verbatim window into the summary.

        Delegates to SessionCompressionContext.compact_now with a persist
        callback. ``recent_keep=0`` frees the entire verbatim turn window so the
        next turn's context is just the (bounded) summary. Used by ``/clear``.
        """
        return self._ctx.compact_now(
            session, model, llm_client, recent_keep=recent_keep,
            notify=notify, persist=lambda: self._save(session),
        )

    def list_sessions(self) -> list[dict[str, Any]]:
        """List all design sessions with basic metadata, newest first.

        Ordering is by recency of use, not by filename: the previous
        ``sorted(glob(...), reverse=True)`` sorted on the session *id* (the JSON
        filename), which only correlates with recency when ids are timestamps
        and breaks for human-readable ids. Sort on ``updated_at`` from the
        stored metadata, falling back to the file's mtime for legacy sessions
        that predate the field, then by id as a stable tie-breaker.
        """
        sessions = []
        try:
            for path in self.sessions_dir.glob("*.json"):
                try:
                    data = json.loads(path.read_text(encoding="utf-8"))
                except Exception:
                    continue
                updated = data.get("updated_at")
                if not isinstance(updated, (int, float)):
                    # Legacy sessions without updated_at: use file mtime so they
                    # still sort meaningfully instead of being pinned to the
                    # bottom (or top) by a None key.
                    try:
                        updated = path.stat().st_mtime
                    except OSError:
                        updated = 0
                sessions.append({
                    "session_id": data.get("session_id", path.stem),
                    "created_at": data.get("created_at"),
                    "updated_at": updated,
                    "turn_count": len(data.get("turns", [])) + data.get("archived_count", 0),
                    "has_summary": bool(data.get("compressed_summary")),
                })
        except Exception:
            pass
        # Sort newest-first by updated_at (float), tie-broken by id for stability.
        sessions.sort(key=lambda s: (s.get("updated_at") or 0, s.get("session_id") or ""), reverse=True)
        return sessions[:20]  # last 20

    def _save(self, session: DesignSession) -> None:
        """Persist session to disk (after merging new turns from other processes).

        Compressed turns (turns[:compressed_up_to]) are moved to an append-only archive
        (.archive.jsonl), leaving only the summary + recent turns in the active JSON file.
        The active file is fully rewritten on every add_turn, so without archiving the
        write cost would grow to O(full history) indefinitely.
        """
        with self._save_lock:
            try:
                with self._flock(session.session_id):
                    self._adopt_from_disk(session)
                    self._reap_zombie_in_progress(session)
                    self._write_session(session)
            except Exception as e:
                logger.warning("Failed to save session %s: %s", session.session_id, e)

    def _write_session(self, session: DesignSession) -> None:
        """Archive migration + atomic active file write (caller must hold lock).

        Uses temp file + os.replace — other processes reading without the lock
        (e.g. get_or_create's mtime refresh) will never see a partial write."""
        self._archive_compressed_turns(session)
        path = self._session_path(session.session_id)
        data = {
            "session_id": session.session_id,
            "created_at": session.created_at,
            "updated_at": session.updated_at,
            "turns": session.turns,
            "compressed_summary": session.compressed_summary,
            "compressed_up_to": session.compressed_up_to,
            "archived_count": session.archived_count,
            "decisions": session.decisions,
            "chat_mode": session.chat_mode,
        }
        tmp = path.with_name(path.name + ".tmp")
        tmp.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
        os.replace(tmp, path)
        try:
            self._mtimes[session.session_id] = path.stat().st_mtime
        except OSError:
            pass

    def _archive_compressed_turns(self, session: DesignSession) -> None:
        """Move compressed turns from active turns to archive file (caller must hold lock).

        preserve=True turns stay in the active file because build_context_messages
        must re-insert their original text into context — stops archiving at the first
        preserve turn.
        Crash recovery: checks the absolute index ("i") of the last archive record to
        skip already-written turns (no duplicates even if the process dies after append
        but before saving the active file).
        """
        local_cut = session.compressed_up_to - session.archived_count
        if local_cut <= 0:
            return
        n = 0
        for t in session.turns[:local_cut]:
            if t.get("preserve"):
                break
            n += 1
        if n <= 0:
            return
        path = self._archive_path(session.session_id)
        try:
            last_i = self._archive_last_index(path)
            with open(path, "a", encoding="utf-8") as f:
                for j, t in enumerate(session.turns[:n]):
                    abs_i = session.archived_count + j
                    if abs_i <= last_i:
                        continue
                    rec = dict(t)
                    rec["i"] = abs_i
                    f.write(json.dumps(rec, ensure_ascii=False) + "\n")
        except Exception as e:
            logger.warning(
                "Failed to archive turns for session %s: %s — keeping turns in active file",
                session.session_id, e,
            )
            return
        session.turns = session.turns[n:]
        session.archived_count += n

    @staticmethod
    def _archive_last_index(path: Path) -> int:
        """Absolute index of the last archive file record. Returns -1 if absent."""
        if not path.exists():
            return -1
        try:
            with open(path, "rb") as f:
                f.seek(0, 2)
                size = f.tell()
                f.seek(max(0, size - 65536))
                tail = f.read().decode("utf-8", errors="replace")
            for line in reversed(tail.strip().split("\n")):
                line = line.strip()
                if line:
                    return int(json.loads(line).get("i", -1))
        except Exception:
            pass
        return -1

    def load_archived_turns(self, session_id: str) -> list[dict[str, Any]]:
        """Load all archived old turns in chronological order (for search_design_history)."""
        path = self._archive_path(session_id)
        if not path.exists():
            return []
        turns: list[dict[str, Any]] = []
        try:
            with open(path, encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        turns.append(json.loads(line))
                    except ValueError:
                        continue  # Skip corrupted lines (partial writes during crash etc.)
        except Exception as e:
            logger.warning("Failed to load archive for session %s: %s", session_id, e)
            return []
        return turns

    @staticmethod
    def _safe_id(session_id: str) -> str:
        return "".join(c for c in session_id if c.isalnum() or c in "-_")

    def archive_path(self, session_id: str) -> Path:
        """Public accessor for a session's archive path (for cache signatures)."""
        return self._archive_path(session_id)

    def _archive_path(self, session_id: str) -> Path:
        return self.sessions_dir / f"{self._safe_id(session_id)}.archive.jsonl"

    def delete_session(self, session_id: str) -> bool:
        """Delete a session from disk and in-memory cache. Returns True if deleted."""
        self._cache.pop(session_id, None)
        self._mtimes.pop(session_id, None)
        self._ctx._compress_locks.pop(session_id, None)
        lock_path = self.sessions_dir / f"{self._safe_id(session_id)}.lock"
        if lock_path.exists():
            try:
                lock_path.unlink()
            except Exception:
                pass
        archive = self._archive_path(session_id)
        if archive.exists():
            try:
                archive.unlink()
            except Exception as e:
                logger.warning("Failed to delete archive %s: %s", session_id, e)
        path = self._session_path(session_id)
        if path.exists():
            try:
                path.unlink()
                return True
            except Exception as e:
                logger.warning("Failed to delete session %s: %s", session_id, e)
        return False

    def _session_path(self, session_id: str) -> Path:
        return self.sessions_dir / f"{self._safe_id(session_id)}.json"
