#!/usr/bin/env python3
"""Check no NEW F821 (undefined name) vs baseline.

Usage:
    python scripts/check_f821_no_new.py          # check for new errors
    python scripts/check_f821_no_new.py <file>.py ...  # check only given files
    python scripts/check_f821_no_new.py --write-baseline  # regenerate baseline

Baseline key: ``<file_path>::<name>`` (file-scoped).

Explicit file args (pre-commit per-file mode) scan only those files — the
full-repo always_run scans were dropped from the hook config because they
created a multi-second window where pre-commit's run-start `git diff` vs
post-hook diff comparison false-positives on parallel-session writes.  No
args (lint.yml CI) still scans the whole repo.  Keys use the same
repo-relative path format in both modes, so the baseline comparison is
identical for the files scanned.
"""

import os
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
BASELINE = REPO / "scripts" / "f821_baseline.txt"


def _resolve_scan_paths(args: list[str]) -> list[str] | None:
    """Normalize explicit file args to repo-relative ``*.py`` paths.

    Returns ``None`` when no file args survive (or none were given) — the
    caller then scans the whole repo, preserving the no-args (lint.yml CI)
    behaviour.  pre-commit passes absolute paths; lint.yml passes none — both
    normalize to the same repo-relative key space as the ``.`` full scan, so
    baseline keys match exactly.
    """
    out: list[str] = []
    for a in args:
        rel = os.path.relpath(Path(a).resolve(), Path(REPO).resolve())
        if rel.endswith(".py") and not rel.startswith(".."):
            out.append(rel)
    return out or None


def _get_current_errors(paths: list[str] | None = None) -> set[str]:
    # timeout= so a hung ruff can never stall the hook/CI forever. A gate must
    # FAIL on timeout (fail-closed), not silently pass on empty output — which is
    # why we do NOT use common/subprocess_utils.run_bounded_subprocess here (that
    # helper swallows timeouts into returncode=-9, a fail-open semantic).
    try:
        result = subprocess.run(
            ["ruff", "check", "--select=F821", "--output-format=concise"]
            + (paths or ["."]),
            capture_output=True, text=True, cwd=REPO, timeout=180,
            check=False,
        )
    except subprocess.TimeoutExpired:
        print("❌ ruff F821 scan timed out after 180s — failing closed rather than risk a silent pass.", file=sys.stderr)
        sys.exit(1)
    # ruff outputs lines like:  file.py:line:col: F821 Undefined name `blah`
    errors: set[str] = set()
    for line in result.stdout.splitlines():
        if "F821" not in line:
            continue
        parts = line.split(":", 3)
        if len(parts) >= 4:
            fpath = parts[0].strip()
            msg = parts[3].strip()
            if "Undefined name" in msg:
                name = msg.split("`")[1].split("`")[0] if "`" in msg else msg
                errors.add(f"{fpath}::{name}")
    return errors


def _load_baseline() -> set[str]:
    if not BASELINE.exists():
        return set()
    baseline: set[str] = set()
    for line in BASELINE.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            baseline.add(stripped)
    return baseline


def _write_baseline(errors: set[str]) -> None:
    BASELINE.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# asicode F821 baseline — KNOWN pre-existing undefined names.\n"
        "#\n"
        "# Generated by `scripts/check_f821_no_new.py --write-baseline`.\n"
        "# Hand-editing is allowed: sorted, one name per line, `#` comments ok.\n"
        "#\n"
    )
    lines = sorted(errors)
    BASELINE.write_text(header + "\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")


def main() -> int:
    paths = _resolve_scan_paths([a for a in sys.argv[1:] if not a.startswith("--")])
    current = _get_current_errors(paths)
    if "--write-baseline" in sys.argv:
        _write_baseline(current)
        print(f"✅ Baseline written: {BASELINE} ({len(current)} entries)")
        return 0

    baseline = _load_baseline()
    new_errors = current - baseline

    if not new_errors:
        print(f"✅ No new F821 errors ({len(current)} total, {len(baseline)} baselined)")
        return 0

    print(f"❌ {len(new_errors)} NEW F821 error(s) found (not in baseline):\n")
    for err in sorted(new_errors):
        print(f"  {err}")
    print(f"\nTotal F821: {len(current)}, Baselined: {len(baseline)}")
    print("Tip: fix the errors above, or run `--write-baseline` if they are pre-existing.")
    return 1


if __name__ == "__main__":
    sys.exit(main())
