#!/usr/bin/env python3
"""Check no NEW F811 (redefinition of unused name) vs baseline.

Usage:
    python scripts/check_f811_no_new.py          # check for new errors
    python scripts/check_f811_no_new.py --write-baseline  # regenerate baseline

Baseline key: ``<file_path>::<line>::<name>`` (line-scoped) because a file can
legitimately accumulate multiple distinct redefinitions at different lines.
"""

import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
BASELINE = REPO / "scripts" / "f811_baseline.txt"


def _get_current_errors() -> set[str]:
    result = subprocess.run(
        ["ruff", "check", "--select=F811", "--output-format=concise", "."],
        capture_output=True, text=True, cwd=REPO,
    )
    errors: set[str] = set()
    for line in result.stdout.splitlines():
        if "F811" not in line:
            continue
        parts = line.split(":", 3)
        if len(parts) >= 4:
            fpath = parts[0].strip()
            lineno = parts[1].strip()
            msg = parts[3].strip()
            if "Redefinition of unused" in msg:
                name = msg.split("`")[1].split("`")[0] if "`" in msg else msg
                errors.add(f"{fpath}::{lineno}::{name}")
    return errors


def _load_baseline() -> set[str]:
    if not BASELINE.exists():
        return set()
    baseline: set[str] = set()
    for line in BASELINE.read_text().splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            baseline.add(stripped)
    return baseline


def _write_baseline(errors: set[str]) -> None:
    BASELINE.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# asicode F811 baseline — KNOWN pre-existing redefinitions of unused names.\n"
        "#\n"
        "# Generated by `scripts/check_f811_no_new.py --write-baseline`.\n"
        "# Hand-editing is allowed: sorted, one per line, `#` comments ok.\n"
        "# Key: <file_path>::<line>::<name>\n"
        "#\n"
    )
    lines = sorted(errors)
    BASELINE.write_text(header + "\n".join(lines) + ("\n" if lines else ""))


def main() -> int:
    current = _get_current_errors()
    if "--write-baseline" in sys.argv:
        _write_baseline(current)
        print(f"✅ Baseline written: {BASELINE} ({len(current)} entries)")
        return 0

    baseline = _load_baseline()
    new_errors = current - baseline

    if not new_errors:
        print(f"✅ No new F811 errors ({len(current)} total, {len(baseline)} baselined)")
        return 0

    print(f"❌ {len(new_errors)} NEW F811 error(s) found (not in baseline):\n")
    for err in sorted(new_errors):
        print(f"  {err}")
    print(f"\nTotal F811: {len(current)}, Baselined: {len(baseline)}")
    print("Tip: fix the errors above, or run `--write-baseline` if they are pre-existing.")
    return 1


if __name__ == "__main__":
    sys.exit(main())
