#!/usr/bin/env python3
"""Check no NEW unreachable AgentConfig bool flags vs baseline.

An ``AgentConfig`` bool field is *reachable* if its name appears in some
non-test ``.py`` file outside its defining module (``tool_registry.py``) — i.e.
something reads/writes it. Fields that only ever take their dataclass default
are *unreachable*: either intentional internal-only config, or dead config
shipped without wiring (the recurring "infra built but never wired" pattern;
e.g. ``prefer_fused_tools`` / ``action_memory_enabled`` were true dead weight).

This guard fails only on NEW unreachable flags not present in the baseline, so
pre-existing debt is grandfathered while regressions are blocked.

Usage:
    python scripts/check_config_flag_reachable.py          # check for new dead flags
    python scripts/check_config_flag_reachable.py --write-baseline  # regenerate baseline

Baseline key: ``<field_name>`` (one per line).
"""
from __future__ import annotations

import ast
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
TOOL_REGISTRY = REPO / "external_llm" / "agent" / "tool_registry.py"
DEFINING_MODULE = "external_llm/agent/tool_registry.py"
BASELINE = REPO / "scripts" / "config_flag_unreachable_baseline.txt"


def _collect_bool_fields() -> list[str]:
    """AST-extract bool-typed fields from the AgentConfig dataclass."""
    tree = ast.parse(TOOL_REGISTRY.read_text(encoding="utf-8"))
    fields: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef) and node.name == "AgentConfig":
            for stmt in node.body:
                # `field: bool = False` → AnnAssign with target id + annotation `bool`
                if isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name):
                    ann = ast.unparse(stmt.annotation)
                    if ann == "bool":
                        fields.append(stmt.target.id)
    return fields


def _is_referenced_outside_defining(field: str) -> bool:
    """True if `field` appears in a non-test .py file outside the defining module.

    Uses `git grep` over tracked Python files (fast; ignores build artifacts).
    Test-only references do NOT count as wiring — a flag set only in tests is
    dead in production.
    """
    result = subprocess.run(
        ["git", "grep", "-l", "-e", field, "--", "*.py"],
        capture_output=True, text=True, cwd=REPO,
    )
    for f in result.stdout.splitlines():
        if not f:
            continue
        if DEFINING_MODULE in f:
            continue
        if f.startswith("tests/"):
            continue
        # Exclude the reachability checkers themselves and other CI scripts in
        # scripts/ — they legitimately mention flag names in docstrings/baselines
        # (e.g. this file's own docstring cites ``prefer_fused_tools`` as a dead
        # example). Without this, committing the checker makes it self-match via
        # git grep and every baselined flag flips to a false-positive "reachable".
        if f.startswith("scripts/"):
            continue
        return True
    return False


def _load_baseline() -> set[str]:
    if not BASELINE.exists():
        return set()
    out: set[str] = set()
    for line in BASELINE.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if s and not s.startswith("#"):
            out.add(s)
    return out


def _write_baseline(flags: set[str]) -> None:
    BASELINE.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# asicode unreachable AgentConfig flags — KNOWN dead/internal-only config.\n"
        "#\n"
        "# Generated by `scripts/check_config_flag_reachable.py --write-baseline`.\n"
        "# Each entry is a bool field defined in AgentConfig but never referenced\n"
        "# outside tool_registry.py (excluding tests). Hand-editing allowed.\n"
        "#\n"
    )
    lines = sorted(flags)
    BASELINE.write_text(header + "\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")


def main() -> int:
    fields = _collect_bool_fields()
    unreachable = {f for f in fields if not _is_referenced_outside_defining(f)}

    if "--write-baseline" in sys.argv:
        _write_baseline(unreachable)
        print(f"✅ Baseline written: {BASELINE} ({len(unreachable)} entries)")
        return 0

    baseline = _load_baseline()
    new_unreachable = unreachable - baseline
    # Also flag fields that vanished from the dataclass but linger in baseline (stale).
    stale = baseline - set(fields)

    if not new_unreachable and not stale:
        print(f"✅ No new unreachable flags ({len(unreachable)} unreachable, {len(baseline)} baselined)")
        return 0

    if new_unreachable:
        print(f"❌ {len(new_unreachable)} NEW unreachable AgentConfig flag(s):\n")
        for f in sorted(new_unreachable):
            print(f"  {f}")
        print(
            "\nThese bool fields are defined in AgentConfig but referenced nowhere outside"
            "\ntool_registry.py (excluding tests). Either wire them to an entry point"
            "\n(CLI/env/profile) or remove them. See design insight 'infra built but"
            "\nnever wired'.\n"
            "Tip: fix, or run `--write-baseline` if intentional."
        )
    if stale:
        print(f"⚠️  {len(stale)} stale baseline entr(ies) (field no longer exists): {sorted(stale)}")
    return 1 if new_unreachable else 0


if __name__ == "__main__":
    sys.exit(main())
