#!/usr/bin/env python3
"""Check no NEW F811 (redefinition of unused name) vs baseline.

Usage:
    python scripts/check_f811_no_new.py          # check for new errors
    python scripts/check_f811_no_new.py --write-baseline  # regenerate baseline

Drift-proof comparison. The baseline stores ``<file_path>::<line>::<name>``
(one entry per occurrence, for human traceability), but the check compares the
COUNT of occurrences per ``<file_path>::<name>`` group, ignoring line numbers.
Editing lines ABOVE a baselined redefinition shifts its line number but never
breaks the match — unlike a naive line-scoped set-difference, which would
false-positive on every such shift. A regression is only when a
``<file>::<name>`` group has MORE occurrences than were baselined.
"""

import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
BASELINE = REPO / "scripts" / "f811_baseline.txt"


def _get_current_errors() -> set[str]:
    # timeout= so a hung ruff can never stall the hook/CI forever. A gate must
    # FAIL on timeout (fail-closed), not silently pass on empty output — which is
    # why we do NOT use common/subprocess_utils.run_bounded_subprocess here (that
    # helper swallows timeouts into returncode=-9, a fail-open semantic).
    try:
        result = subprocess.run(
            ["ruff", "check", "--select=F811", "--output-format=concise", "."],
            capture_output=True, text=True, cwd=REPO, timeout=180,
        )
    except subprocess.TimeoutExpired:
        print("❌ ruff F811 scan timed out after 180s — failing closed rather than risk a silent pass.", file=sys.stderr)
        sys.exit(1)
    errors: set[str] = set()
    for line in result.stdout.splitlines():
        if "F811" not in line:
            continue
        parts = line.split(":", 3)
        if len(parts) >= 4:
            fpath = parts[0].strip()
            lineno = parts[1].strip()
            msg = parts[3].strip()
            if "Redefinition of unused" in msg:
                name = msg.split("`")[1].split("`")[0] if "`" in msg else msg
                errors.add(f"{fpath}::{lineno}::{name}")
    return errors


def _load_baseline() -> set[str]:
    if not BASELINE.exists():
        return set()
    baseline: set[str] = set()
    for line in BASELINE.read_text().splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            baseline.add(stripped)
    return baseline


def _to_count_map(errors: set[str]) -> dict[str, int]:
    """Group ``<file>::<line>::<name>`` keys by ``<file>::<name>`` → occurrence count.

    The line number is dropped so the grouping is stable under line drift
    (insertions/deletions above a baselined redefinition). ``rsplit`` keeps any
    ``::`` inside a file path with the file component.
    """
    counts: dict[str, int] = {}
    for key in errors:
        try:
            rest, name = key.rsplit("::", 1)
            file_part, _line = rest.rsplit("::", 1)
            grouped = f"{file_part}::{name}"
        except ValueError:
            grouped = key  # malformed; fall back to exact key
        counts[grouped] = counts.get(grouped, 0) + 1
    return counts


def _write_baseline(errors: set[str]) -> None:
    BASELINE.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# asicode F811 baseline — KNOWN pre-existing redefinitions of unused names.\n"
        "#\n"
        "# Generated by `scripts/check_f811_no_new.py --write-baseline`.\n"
        "# Hand-editing is allowed: sorted, one per line, `#` comments ok.\n"
        "# Key: <file_path>::<line>::<name> (line is for traceability only; the\n"
        "# check compares per-<file_path>::<name> COUNT, so line drift above a\n"
        "# baselined redefinition never breaks the match).\n"
        "#\n"
    )
    lines = sorted(errors)
    BASELINE.write_text(header + "\n".join(lines) + ("\n" if lines else ""))


def main() -> int:
    current = _get_current_errors()
    if "--write-baseline" in sys.argv:
        _write_baseline(current)
        print(f"✅ Baseline written: {BASELINE} ({len(current)} entries)")
        return 0

    current_counts = _to_count_map(current)
    baseline_counts = _to_count_map(_load_baseline())
    # A regression is any <file>::<name> group that now has MORE occurrences
    # than were baselined (baseline defaults to 0 for unseen groups).
    regressions = {
        k: (cur, baseline_counts.get(k, 0))
        for k, cur in current_counts.items()
        if cur > baseline_counts.get(k, 0)
    }

    if not regressions:
        print(f"✅ No new F811 errors ({len(current)} total, {len(baseline_counts)} baselined groups)")
        return 0

    print(f"❌ {len(regressions)} NEW F811 redefinition group(s) exceeding baseline:\n")
    for k in sorted(regressions):
        cur, base = regressions[k]
        print(f"  {k}: {cur} now (baseline {base})")
    print(f"\nTotal F811: {len(current)}, Baselined groups: {len(baseline_counts)}")
    print("Tip: fix the errors above, or run `--write-baseline` if they are pre-existing.")
    return 1


if __name__ == "__main__":
    sys.exit(main())
