"""routing_policy — learned patch strategy routing policy loader.

Loads a policy JSON file generated by `patch_strategy_bench.py learn-policy`
and provides a predict() function used by _attach_edit_contracts().

Policy file: ~/.asicode/routing_policy.json
Format:
  {
    "version": 1,
    "rules": [
      {
        "id": "bugfix_large_deep",
        "conditions": {"action_hint": "bugfix", "size_bucket": "large", "nesting": "deep"},
        "recommended_mode": "replace_symbol_body",
        "success_rate": 0.78,
        "n": 12,
        "gain_over_alternative": 0.22
      },
      ...
    ]
  }

Rule matching priority: most conditions → least conditions (most specific first).
Returns None when no rule matches — caller keeps its default.
"""
from __future__ import annotations

import json
import logging
import os
import time
from typing import Any, Optional

from .config.thresholds import config as _cfg

logger = logging.getLogger(__name__)

POLICY_PATH = os.path.expanduser("~/.asicode/routing_policy.json")

# ── Bucket helpers (kept in sync with patch_strategy_bench.py) ────────────────

def _size_bucket(lines: int) -> str:
    if lines <= 0:  return "unknown"
    if lines < 30:  return "small"
    if lines < 80:  return "medium"
    if lines < 200: return "large"
    return "xlarge"


def _nesting_bucket(depth: int) -> str:
    if depth >= 4: return "deep"
    if depth >= 2: return "moderate"
    return "flat"


# ── Policy cache ──────────────────────────────────────────────────────────────

_CACHE_TTL = _cfg.counts.ROUTING_POLICY_CACHE_TTL_S
_cached_policy: Optional["RoutingPolicy"] = None
_cached_mtime: float = 0.0
_last_check: float = 0.0


class RoutingPolicy:
    """Immutable policy loaded from a JSON file."""

    def __init__(self, rules: list[dict[str, Any]]):
        # Sort: most conditions first (most specific wins)
        self._rules = sorted(rules, key=lambda r: -len(r.get("conditions", {})))

    def predict(
        self,
        action_hint: str,
        sym_lines: int = 0,
        nested_depth: int = 0,
    ) -> Optional[str]:
        """Return recommended mode or None if no rule matches.

        Parameters
        ----------
        action_hint:   value from op.metadata['action_hint']
        sym_lines:     line count of the target symbol (0 = unknown)
        nested_depth:  max block nesting depth (0 = unknown / flat)
        """
        if not action_hint:
            return None

        sb = _size_bucket(sym_lines)
        nb = _nesting_bucket(nested_depth)

        for rule in self._rules:
            cond = rule.get("conditions", {})
            if not _matches(cond, action_hint, sb, nb):
                continue
            mode = rule.get("recommended_mode", "")
            # ast_op = targeted/surgical change; normalize to surgical_edit for contract routing
            if mode == "ast_op":
                mode = "surgical_edit"
            if mode in ("surgical_edit", "replace_symbol_body"):
                logger.debug(
                    "routing_policy: %s matched rule %r → %s (rate=%.2f n=%d)",
                    action_hint, rule.get("id", "?"), mode,
                    rule.get("success_rate", 0), rule.get("n", 0),
                )
                return mode
        return None

    def __len__(self) -> int:
        return len(self._rules)


def _matches(cond: dict[str, str], action_hint: str, size_bucket: str, nesting: str) -> bool:
    if "action_hint" in cond and cond["action_hint"] != action_hint:
        return False
    if "size_bucket" in cond and cond["size_bucket"] != size_bucket:
        return False
    if "nesting" in cond and cond["nesting"] != nesting:
        return False
    return True


def load_policy() -> Optional[RoutingPolicy]:
    """Return current RoutingPolicy, or None if no valid policy file exists.

    Results are cached for _CACHE_TTL seconds. Thread-safety is not required
    (worst case: two threads both load the file once).
    """
    global _cached_policy, _cached_mtime, _last_check

    now = time.monotonic()
    if now - _last_check < _CACHE_TTL:
        return _cached_policy
    _last_check = now

    if not os.path.exists(POLICY_PATH):
        _cached_policy = None
        return None

    try:
        mtime = os.path.getmtime(POLICY_PATH)
        if mtime == _cached_mtime and _cached_policy is not None:
            return _cached_policy

        with open(POLICY_PATH, encoding="utf-8") as f:
            data = json.load(f)

        rules = data.get("rules", [])
        _cached_policy = RoutingPolicy(rules) if rules else None
        _cached_mtime = mtime
        if _cached_policy:
            logger.info("routing_policy: loaded %d rules from %s", len(_cached_policy), POLICY_PATH)
        return _cached_policy

    except Exception as e:
        logger.debug("routing_policy: failed to load %s: %s", POLICY_PATH, e)
        _cached_policy = None
        return None
